metrotify/aplicacion/usuario/urls.py
from django.urls import path

from . import views

app_name = "usuario_app"

urlpatterns = [
    path(
        'api/registrar', 
        views.UserRegistrationAPIView.as_view(),
        name='api-perfil-registrar',
    ),
     path(
        'registrar', 
        views.RegistroCreateView.as_view(),
        name='auth_registrar',
    ),
    path(
        '', 
        views.LoginView.as_view(),
        name='auth-login',
    ),
    path(
        'perfil-update/<str:pk>/',
        views.UserUpdateView.as_view(),
        name='usuario_update',
    ),
    path('eliminar-cuenta/<str:pk>/', 
         views.UserDeleteView.as_view(), 
         name='eliminar_cuenta'),

    path('cambiar-contrasena/<str:pk>/', 
         views.UpdatePasswordView.as_view(), 
         name='cambiar_password'),

    path(
        'home/', 
        views.HomePruebaView.as_view(),
        name='home',
    ),
    path(
        'detallar-usuario/<str:pk>/usuario/<str:usuario_id>',
        views.UsuarioDetailView.as_view(),
        name='usuario_detallar',
    ),
     path('importar-usuarios/', views.import_users, name='importar_usuarios'),
    path('search-users/', views.search_users, name='search_users'),
     path(
        'prueba/', 
        views.HomePruebaView.as_view(),
        name='home-prueba',
    ),
     path(
        'usuario/logout/', 
        views.LogoutView.as_view(),
        name='usuario-logout',
    ),

]

metrotify/metrotify/urls.py
from django.contrib import admin
from django.urls import include, path,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('aplicacion.usuario.urls')),

]

metrotify/aplicacion/usuario/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from model_utils.models import TimeStampedModel
from django.contrib.auth.models import Group
from .managers import *
from djongo import models
from aplicacion.musical.models import * 
from aplicacion.musical.forms import * 
from conection_db import db

usuario_db=db['usuario']

class User(AbstractBaseUser,TimeStampedModel,PermissionsMixin):
    NOMBRE_CHOICES = [
        ('Musico', 'listener'),
        ('Escuchas', 'musician'),
    ]
    id = models.CharField(primary_key=True, max_length=200)
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    type = models.CharField(max_length=30, choices=NOMBRE_CHOICES)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser=models.BooleanField(default=False)
    groups = models.ManyToManyField(Group, related_name='usuario_groups')
    is_deleted=models.BooleanField(default=False)
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='usuario_user_permissions',
        blank=True,
        help_text='The permissions this user has.',
        verbose_name='user permissions',
    )
    
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['name']

    objects = UserManager()
    
    def __str__(self):
        return self.name

metrotify/aplicacion/usuario/forms.py
from django import forms
from .models import *

from django.contrib.auth import authenticate

class RegistroForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña',
                'class':  'form-control',
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña',
                'class':  'form-control',
            }
        )
    )

    class Meta:
        model = User
        fields = ['name', 'email', 'username', 'type']
        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'Correo Electronico ...','class': 'form-control'}, ),
            'username': forms.TextInput(
                attrs={'placeholder': 'Usuario ...','class': 'form-control'}, ),
            'email': forms.EmailInput(attrs={'placeholder': 'Nombre y Apellido ...', 'class': 'form-control'},),
            'type': forms.Select(attrs={'placeholder': 'Tipo de Usuario ...','class': 'form-control'}),
        }

        def clean_password2(self):
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    email = forms.CharField(
        label='Correo Electronico',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Correo Electronico',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        print("entre aqui incorrecta las user", email, "password",  password)
        if not email:
            raise forms.ValidationError('El correo electrónico es obligatorio.')
        if not password:
            raise forms.ValidationError('La contraseña es obligatoria.')
            
        return self.cleaned_data
    


class UserUpdateForm(forms.ModelForm):
    
    class Meta:
        model = User  # Especifica la clase de modelo User
        fields = ['name', 'email', 'username', 'type']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Nombre y Apellido ...','class': 'form-control'}),
            'username': forms.TextInput(attrs={'placeholder': 'Usuario ...','class': 'form-control'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Correo Electronico ...', 'class': 'form-control'}),
            'type': forms.Select(attrs={'placeholder': 'Tipo de Usuario ...','class': 'form-control'}),
        }



class UpdatePasswordForm(forms.Form):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Actual'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Nueva'
            }
        )
    )

metrotify/aplicacion/usuario/views.py
from django.shortcuts import render
from django.contrib import messages
from django.utils.html import strip_tags
import requests
import json
from itertools import chain
import urllib.request
# Create your views here.
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import UserRegistrationSerializer
from .models import *
from .forms import *
from django.views.generic import (
    ListView, TemplateView, 
    CreateView, UpdateView, DeleteView, DetailView, View ,)
from django.http import JsonResponse
from django.views.generic.edit import (
    FormView
)
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
#
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect
from bson import ObjectId
from aplicacion.musical.models import *
from django.db import models

from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    RetrieveAPIView,
    DestroyAPIView,
    UpdateAPIView,
    RetrieveUpdateAPIView,
)
from django.http import Http404
from .managers import *

# class UserRegistrationAPIView(APIView):
#     def post(self, request):
#         serializer = UserRegistrationSerializer(data=request.data)
#         if serializer.is_valid():
#             user = serializer.save()
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RegistroCreateView(FormView):
    model = User
    form_class = RegistroForm
    template_name = 'auth/registro.html'
    success_url = reverse_lazy('usuario_app:auth-login')  # Reemplaza 'ruta_hacia_exitoso' con la URL a la que deseas redirigir después de registrar exitosamente

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            type=form.cleaned_data['type'],
            name=form.cleaned_data['name'],
            username=form.cleaned_data['username']
        )
        # enviar el codigo al email del user
        return super(RegistroCreateView, self).form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, '¡Error! Por favor, corrige los errores en el formulario.')
        
        return self.render_to_response(self.get_context_data(form=form))


class LoginView(FormView):
    template_name = 'auth/login.html'
    model=User
    form_class = LoginForm
    success_url = reverse_lazy('usuario_app:home')
    
    def form_valid(self, form):
        try:
            user = User.objects.get(email=form.cleaned_data['email'])
            print("usuario no registrado ", user)
            if user.is_deleted:
                messages.error(self.request, 'Correo  electronico no registrado.' )
                return self.render_to_response(self.get_context_data(form=form))
        except User.DoesNotExist :
                messages.error(self.request, 'Correo  electronico no registrado.')
                return self.render_to_response(self.get_context_data(form=form))

        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        if user is not None:
            login(self.request, user)
            print("if user is not None:")
            return super(LoginView, self).form_valid(form)
        else:
            error_message = 'Credenciales inválidas. Por favor, inténtalo de nuevo.' 
            messages.error(self.request, 'Credenciales inválidas. Por favor, inténtalo de nuevo.' )
       
            return self.render_to_response(self.get_context_data(form=form))
        
    def form_invalid(self, form):
        # Dentro de tu método de vista
        messages.error(self.request, 'Credenciales inválidas. Por favor, inténtalo de nuevo.' )
        return self.render_to_response(self.get_context_data(form=form))


class LogoutView(View):
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'usuario_app:auth-login'
            )
        )


class UserUpdateView(LoginRequiredMixin,UpdateView):
    template_name = "usuario/updatePerfil.html"
    form_class = UserUpdateForm
    model = User
    context_object_name = "usuario"
    success_url =reverse_lazy('usuario_app:home')
    
    def get_object(self, queryset=None):
        user_id = self.kwargs.get('pk')
        user = User.objects.get(id=user_id)
        return user #User.objects.get(id=ObjectId(user_id))


class UserDeleteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print(pk)
        user_id = pk #self.kwargs.get('pk')
        
        user = User.objects.get(id=user_id) #User.objects.get(_id=ObjectId(user_id))
        user.is_deleted = True
        user.email= user.email + "eliminado"
        user.save()
       
        return HttpResponseRedirect(
            reverse(
                'usuario_app:auth-login'
            )
        )


class UpdatePasswordView(LoginRequiredMixin, FormView):
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)



def import_users(request):
    urlLinkUsuario = 'https://raw.githubusercontent.com/Algoritmos-y-Programacion/api-proyecto/main/users.json'
    urlMusica='https://raw.githubusercontent.com/Algoritmos-y-Programacion/api-proyecto/main/albums.json'
    urlPl=' https://raw.githubusercontent.com/Algoritmos-y-Programacion/api-proyecto/main/playlists.json'
    
    try:
        response = requests.get(urlLinkUsuario)
        response.raise_for_status()  # Raise an exception for non-2xx status codes
        responseMusica = requests.get(urlMusica)
        responseMusica.raise_for_status()  # Raise an exception for non-2xx status codes
        
        responsePlay = requests.get(urlPl)
        responsePlay.raise_for_status()  # Raise an exception for non-2xx status codes
        
        if response.status_code == 200 and responseMusica.status_code == 200 and responsePlay.status_code == 200:
            # data = json.loads(response.content)
            # dataMusica=json.loads(responseMusica.content)
            # dataPlay=json.loads(responsePlay.content)
            # usuario_db.insert_many(data)
            # for user_data in data:
            #     print(user_data)
            #     user = User.objects.create_user(
            #         id=user_data['id'],
            #         name=user_data['name'],
            #         email=user_data['email'],
            #         username=user_data['username'],
            #         type=user_data['type'],
            #         password="123456"
            #     )
            #     user.save()
        
            # for musica_data in dataMusica:
            #     artist_id = musica_data['artist']
            #     print("artist_id ", artist_id)
            #     print("artist_id ", musica_data)
            #     album = Album.objects.create(
            #         id=data['id'],
            #         name=musica_data['name'],
            #         description=musica_data['description'],
            #         cover=musica_data['cover'],
            #         published=datetime.strptime(musica_data['published'], '%Y-%m-%dT%H:%M:%S.%fZ'),
            #         genre=musica_data['genre'],
            #         artist=musica_data['artist']
            #     )
            #     for i in range(len(data['tracklist'])): 

            #         track_data = data['tracklist'][i]
            #         track = Track.objects.create(
            #             id=track_data['id'],
            #             name=track_data['name'],
            #             duration=track_data['duration'],
            #             link=track_data['link']
            #         )
            #         track.save()
            #         album.tracklist.append(ObjectId(track._id))

            #     album.save()

            # for play_data in dataPlay:
               
            #     creator_id = play_data['artist']
            #     creator = User.objects.get(id=creator_id)

            #     playList = Playlist.objects.create(
            #         id=play_data['id'],
            #         name=play_data['name'],
            #         description=play_data['description'],
            #         creator=creator,
                    
            #     )
            #     playList_data = play_data['tracklist']
            #     for list in playList_data:
            #         creatorPlayList = Track.objects.get(id=list)
            #         playList.tracks.append(creatorPlayList)

            #     playList.save()


            return  HttpResponseRedirect(reverse('usuario_app:auth-login'))
    
    except Exception as e:
        # Manejar cualquier error que pueda ocurrir durante la importación de usuarios
        # Puedes mostrar un mensaje de error o realizar alguna otra acción aquí
        print(f"Error al importar usuarios: {e}")
        return    HttpResponseRedirect(reverse('usuario_app:auth-login'))
    
    
# def search_users(request):
#     if request.method == 'GET':
#         search_query = request.GET.get('q', '')  # Obtiene el parámetro de búsqueda de la URL

metrotify/templates/usuario/base_usuario.html
{% extends "menu.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

metrotify/templates/usuario/contenedorHome.html
<section class="d-flex flex-column justify-content-center align-items-center border border-2 rounded-1" style="width: 80%; margin: auto;">

  <section class="container-fluid mt-4 d-flex justify-content-evenly" style="width: 100%;">
      <button type="button" class="btn btn-secondary btn-lg">Álbumes Favoritos </button>
      <button type="button" class="btn btn-secondary btn-lg">Canciones Favoritas</button>
      <button type="button" class="btn btn-secondary btn-lg">Playlist Creados</button>
  </section>

  <section class="container-fluid mt-3 mb-3">
      <div class="row row-cols-3">
          {% if playlistArray %}
              {% for playlist in playlistArray %}
                  <div class="col  mt-4">
                      <div class="card h-100">
                          <div class="card-body d-flex flex-column">
                            <i class="bi bi-music-note-beamed"></i>
                              <h5 class="card-title">{{ playlist.name }}</h5>
                              <p class="card-text flex-grow-1">{{ playlist.description}}</p>
                              <a href="#" class="btn btn-primary mt-auto">Ver más</a>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          {% else %}
              <div class="col">
                  <h3 style="color: red;">No hay playlists disponibles</h3>
              </div>
          {% endif %}
      </div>
  </section>

</section>





<!-- 
<section class="d-flex flex-column justify-content-center align-items-center border border-2 rounded-1 " style="width: 80%; margin: auto;">

        <section class=".container-fluid mt-4 d-flex justify-content-evenly" style="width: 100%;">
            <button type="button" class="btn btn-secondary btn-lg">Álbumes Creados</button>
            <button type="button" class="btn btn-secondary btn-lg">Canciones Favoritos</button>
            <button type="button" class="btn btn-secondary btn-lg">Playlist creados </button>
        </section>
        <section class=".container-fluid mt-3 mb-3 d-flex justify-content-evenly" style="width: 100%;">
          {% if playlistArray %}
              {% for playlist in playlistArray %}
                  
                  <div class="card" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{playlist.name}}</h5>
                      <p class="card-text">{{playlist.description}}</p>
                      <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                  </div>
              {% endfor %}
      {% else %}
          <h3 style="color:red"> No hay playlists disponibles </h3>
      {% endif %}
        </section>
    </section>
</section> -->

metrotify/templates/usuario/contenedorHomeMusico.html
<section class="d-flex flex-column justify-content-center align-items-center border border-2 rounded-1" style="width: 80%; margin: auto;">

    <section class="container-fluid mt-4 d-flex justify-content-evenly" style="width: 100%;">
        <button type="button" class="btn btn-secondary btn-lg" onclick="mostrarContenido('collapseAlbum')">Álbumes </button>
        <button type="button" class="btn btn-secondary btn-lg" onclick="mostrarContenido('collapseTopCancion')">Top 10 de Canciones</button>
        <button type="button" class="btn btn-secondary btn-lg" onclick="mostrarContenido('collapsePlayList')">Playlist Creados</button>
        <button type="button" class="btn btn-secondary btn-lg" onclick="mostrarContenido('collapseReproducciones')">Cantidad de Reproducciones</button>
    </section>
  
    <section id='collapseAlbum' class="container-fluid mt-3 mb-3">
        <div class="row row-cols-3">
            {% if albunesArray %}
                {% for album in albunesArray %}
                    <div class="col  mt-4">
                        <div class="card h-100">
                            <div class="card-body d-flex flex-column">
                              <i class="bi bi-music-note-beamed"></i>
                                <h5 class="card-title">{{ album.name }}</h5>
                                <p class="card-text flex-grow-1">{{ album.description}}</p>
                                <p class="card-text flex-grow-1">Publicado {{ album.published}} -  Genero {{album.genre}}</p>
                                <p class="card-text flex-grow-1">Genero {{album.genre}}</p>
                                <div class="d-flex justify-content-between mt-auto">
                                    <a href="#" class="btn btn-primary">Ver más</a>
                                    <button type="button" class="btn btn-outline-primary"><i class="bi bi-heart"></i> Like</button>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col">
                    <h3 style="color: red;">No hay playlists disponibles</h3>
                </div>
            {% endif %}
        </div>
   </section>
    
    <section id="collapseTopCancion" class="container-fluid mt-3 mb-3" style="display: none;">
      <h2>Canciones Favoritas</h2>
      <p>Aquí puedes mostrar las canciones favoritas</p>
    </section>
  
    <section id="collapsePlayList" class="container-fluid mt-3 mb-3" style="display: none;">
        <div class="row row-cols-3">
            {% if playlistArray %}
                {% for playlist in playlistArray %}
                    <div class="col  mt-4">
                        <div class="card h-100">
                            <div class="card-body d-flex flex-column">
                              <i class="bi bi-music-note-beamed"></i>
                                <h5 class="card-title">{{ playlist.name }}</h5>
                                <p class="card-text flex-grow-1">{{ playlist.description}}</p>
                                <a href="#" class="btn btn-primary mt-auto">Ver más</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col">
                    <h3 style="color: red;">No hay playlists disponibles</h3>
                </div>
            {% endif %}
        </div>
    </section>
  
    <section id="collapseReproducciones" class="container-fluid mt-3 mb-3" style="display: none;">
      <h2>Cantidad de Reproducciones</h2>
      <p>Aquí puedes mostrar la cantidad de reproducciones</p>
    </section>
  </section>
  
  <script>
    // Función para mostrar el contenido de una sección y ocultar las demás
    function mostrarContenido(id) {
      // Obtener todas las secciones
      var secciones = document.querySelectorAll('section[id^="collapse"]');
      
      // Iterar sobre las secciones y mostrar u ocultar según corresponda
      secciones.forEach(function(seccion) {
        if (seccion.id === id) {
          seccion.style.display = 'block';
        } else {
          seccion.style.display = 'none';
        }
      });
    }
  </script>
  

<!-- <section class="d-flex flex-column justify-content-center align-items-center border border-2 rounded-1" style="width: 80%; margin: auto;">

  <section class="container-fluid mt-4 d-flex justify-content-evenly" style="width: 100%;">
      <button type="button" class="btn btn-secondary btn-lg"
        data-bs-toggle="collapse" data-bs-target="#collapseAlbum" aria-expanded="false" aria-controls="collapseAlbum"
      >Álbumes </button>
      <button type="button" class="btn btn-secondary btn-lg"
      data-bs-toggle="collapse" data-bs-target="#collapseTopCancion" aria-expanded="false" aria-controls="collapseTopCancion"
      >Top 10 de Canciones</button>
      <button type="button" class="btn btn-secondary btn-lg"
      data-bs-toggle="collapse" data-bs-target="#collapsePlayList" aria-expanded="false" aria-controls="collapsePlayList"
      >Playlist Creados</button>
      <button type="button" class="btn btn-secondary btn-lg"
      data-bs-toggle="collapse" data-bs-target="#collapseReproduciones" aria-expanded="false" aria-controls="collapseReproduciones"
      >Cantidad de Reproduciones</button>
  </section>

  <section id='collapseAlbum' class="collapse container-fluid mt-3 mb-3">
    <div class="row row-cols-3">
        {% if playlistArray %}
            {% for playlist in playlistArray %}
                <div class="col  mt-4">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column">
                          <i class="bi bi-music-note-beamed"></i>
                            <h5 class="card-title">{{ playlist.name }}</h5>
                            <p class="card-text flex-grow-1">{{ playlist.description}}</p>
                            <a href="#" class="btn btn-primary mt-auto">Ver más</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col">
                <h3 style="color: red;">No hay playlists disponibles</h3>
            </div>
        {% endif %}
    </div>
 </section>
  
    <section id="collapseTopCancion" class="collapse">

        <div >
            <h2>Canciones Favoritas</h2>
            <p>Aquí puedes mostrar las canciones favoritas</p>
        </div>

    </section>
    <section id="collapsePlayList" class="collapse">
        <div>
            <h2>Playlist Creados</h2>
            <p>Aquí puedes mostrar las playlists creadas</p>
        </div>

    </section>
        <section id="collapsePlayList" class="collapse">
            <div>
                <h2>Playlist Creados</h2>
                <p>Aquí puedes mostrar las playlists creadas</p>
            </div>

        </section>
</section>
{% block js %}
<!-- <script>
  $(document).ready(function() {
    // Ocultar todos los contenidos al principio
    $('#content-section div').hide();

    // Mostrar el contenido correspondiente cuando se hace clic en un botón
    $('#btn-albumes').click(function() {
      $('#content-section div').hide();
      $('#albumes-content').show();
    });

    $('#btn-canciones').click(function() {
      $('#content-section div').hide();
      $('#canciones-content').show();
    });

    $('#btn-playlist').click(function() {
      $('#content-section div').hide();
      $('#playlist-content').show();
    });
  });
</script>

{% endblock js %} -->

<!-- 
<section class="d-flex flex-column justify-content-center align-items-center border border-2 rounded-1 " style="width: 80%; margin: auto;">

        <section class=".container-fluid mt-4 d-flex justify-content-evenly" style="width: 100%;">
            <button type="button" class="btn btn-secondary btn-lg">Álbumes Creados</button>
            <button type="button" class="btn btn-secondary btn-lg">Canciones Favoritos</button>
            <button type="button" class="btn btn-secondary btn-lg">Playlist creados </button>
        </section>
        <section class=".container-fluid mt-3 mb-3 d-flex justify-content-evenly" style="width: 100%;">
          {% if playlistArray %}
              {% for playlist in playlistArray %}
                  
                  <div class="card" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{playlist.name}}</h5>
                      <p class="card-text">{{playlist.description}}</p>
                      <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                  </div>
              {% endfor %}
      {% else %}
          <h3 style="color:red"> No hay playlists disponibles </h3>
      {% endif %}
        </section>
    </section>
</section> --> -->

metrotify/templates/usuario/modalCambiarPassword.html
  <!-- Modal -->
  <div class="modal fade" id="cambiarPassword" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Cambiar contrasena</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <!-- <form action="{% url 'usuario_app:cambiar_password' usuario.pk %}"method="POST" class="cell"> {% csrf_token %} --> 
          <form action="#" method="POST" class="cell"> {% csrf_token %}
            <div class="row">
               
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Contrasena Actual</label>
                   <!-- {{form.password1}} -->
                    <input type="password" class="form-control" id="password1" placeholder="Contrasena Actual">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Confirmar Nueva</label>
                    <!-- {{form.password2}} -->
                    <input type="password" class="form-control" id="password2" placeholder="Contrasena Nueva">
                </div>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Aceptar</button>

        </form>
      </form>
        </div>
      </div>
    </div>
  </div>

metrotify/templates/usuario/modalEliminarCuenta.html
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="staticBackdropLabel">Confirmar Eliminación</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <p>¿Estás seguro de que deseas eliminar tu cuenta?</p>
  
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            <form action="{% url 'usuario_app:eliminar_cuenta' usuario.pk %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Eliminar Cuenta</button>
          </form>
          </div>
        </div>
      </div>
    </div>